### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [brunomacedo/zsh-auto-pnpm-use#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by brunomacedo** [comment]
> I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.
> 
> Please add a license file - if you don't have one in mind, I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.
> 
> Thanks!

Oh, that’s great to hear! I was using it as a personal project and didn’t realize a license was needed. I’ll check out the link you provided to find the best one to add. Thanks!
